import type { Metadata } from "next";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import QueryProviders from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/components/theme-switcher/ui/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased min-h-screen", inter.className)}
        suppressHydrationWarning>
          <QueryProviders>
            <ThemeProvider>
              {children}
              <Toaster />
              <ReactQueryDevtools />
            </ThemeProvider>
          </QueryProviders>
      </body>
    </html>
  );
}
